apiVersion: v1
kind: Service
metadata:
  name: simpleorder
  namespace: tutorial
  labels:
    app: simpleorder
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: simpleorder
