apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleorderhome
  namespace: tutorial
  labels:
    app: simpleorderhome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleorderhome
  template:
    metadata:
      labels:
        app: simpleorderhome
    spec:
      containers:
        - name: simpleorderhome
          image: user23.azurecr.io/simpleorderhome:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
