apiVersion: v1
kind: Service
metadata:
  name: simpleorderhome
  namespace: tutorial
  labels:
    app: simpleorderhome
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: simpleorderhome
